# -*- coding: utf-8 -*-
"""noFace.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15OSXnigtdhHGD0PoJakRYcCdZOuDbQVH
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

image_path = "/content/11.jpg"
mask_path = "/content/eff1.png"
image = cv2.imread(image_path, cv2.IMREAD_COLOR)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
mask = cv2.imread(mask_path, cv2.IMREAD_UNCHANGED)
mask = cv2.resize(mask, (image.shape[1], image.shape[0]))
def apply_mask(image, mask):
    if mask.shape[2] == 4:
        alpha_mask = mask[:, :, 3] / 255.0
        mask_rgb = mask[:, :, :3]

        for c in range(3):
            image[:, :, c] = (1 - alpha_mask) * image[:, :, c] + alpha_mask * mask_rgb[:, :, c]
    return image
masked_image = apply_mask(image.copy(), mask)
plt.figure(figsize=(8, 4))
plt.subplot(1, 2, 1)
plt.imshow(image)
plt.title('Original')
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(masked_image)
plt.title('With Mask')
plt.axis('off')

import cv2
import numpy as np
import matplotlib.pyplot as plt

image_path = "/content/11.jpg"
mask_path = "/content/eff6.png"
image = cv2.imread(image_path, cv2.IMREAD_COLOR)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
mask = cv2.imread(mask_path, cv2.IMREAD_UNCHANGED)
mask = cv2.resize(mask, (image.shape[1], image.shape[0]))
def apply_mask(image, mask):
    if mask.shape[2] == 4:
        alpha_mask = mask[:, :, 3] / 255.0
        mask_rgb = mask[:, :, :3]

        for c in range(3):
            image[:, :, c] = (1 - alpha_mask) * image[:, :, c] + alpha_mask * mask_rgb[:, :, c]
    return image
masked_image = apply_mask(image.copy(), mask)
plt.figure(figsize=(8, 4))
plt.subplot(1, 2, 1)
plt.imshow(image)
plt.title('Original')
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(masked_image)
plt.title('With Mask')
plt.axis('off')